# Automatically list available commands if the user types 'just' with no arguments
default:
    @just --list

# Bind the encrypted drive to the TPM for automatic unlocking
lock-drive:
    sudo systemd-cryptenroll --tpm2-device=auto --tpm2-pcrs=7 /dev/nvme0n1p3

# Update both the base operating system and user applications
update-all:
    sudo bootc upgrade
    flatpak update -y